#!/bin/bash
# Reset the trading agent to its initial state.
# This deletes all trading history, positions, reports, and cycle data.
# strategy.md and core-principles.md are reset to blank templates.
# The briefing document is preserved (not generated by the agent).

set -e

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
cd "$SCRIPT_DIR"

echo "=== Polymarket Agent Reset ==="
echo ""
echo "This will delete:"
echo "  - trading.db (all trades, positions, decisions)"
echo "  - state/strategy.md (agent-evolved rules)"
echo "  - state/performance.md (outcome tracking)"
echo "  - state/reports/ (all cycle reports)"
echo "  - state/cycles/ (all cycle data)"
echo ""
read -p "Are you sure? (y/N): " confirm
if [[ "$confirm" != "y" && "$confirm" != "Y" ]]; then
    echo "Aborted."
    exit 0
fi

# Remove database
if [ -f trading.db ]; then
    rm trading.db
    echo "Deleted trading.db"
fi

# Remove cycle data and reports
if [ -d state/cycles ]; then
    rm -rf state/cycles
    mkdir -p state/cycles
    echo "Cleared state/cycles/"
fi

if [ -d state/reports ]; then
    rm -rf state/reports
    mkdir -p state/reports
    echo "Cleared state/reports/"
fi

# Reset strategy to blank
cat > state/strategy.md << 'EOF'
# Strategy

This document is updated by the trading agent after each cycle.
It starts blank and evolves based on trading experience.
EOF
echo "Reset state/strategy.md"

# Reset performance tracker
cat > state/performance.md << 'EOF'
# Performance Tracker

Cumulative outcome analysis across trading cycles.
EOF
echo "Reset state/performance.md"

# Do NOT touch core-principles.md — that's operator-managed

echo ""
echo "Reset complete. Agent is ready for a fresh start."
